### ISSUE TITLE
problem with maps on phpbb

### ISSUE THREAD

**Issue by eddmax** [MapBBCode/mapbb-phpbb32#1]
greetings

I m new to phpBB and trying to setup a small forum for friends,
my system runs the latest 3-2.7 phpBB and I installed that extension without any errors, therefore this displays only one map per thread, the next post after that will display only text like [MAP]blah blah[/MAP]

I read this error exist on your other version for phpbb 3.1 , was this extension supposed to be compatible with phpbb 3-2.x or I misunderstand that ?

Edward

**Comment by Zverik** [comment]
Hi, this issue is still there. I'll try solving it later, when my conferences are over.

**Comment by eddmax** [comment]
thank you!

**Comment by Unixware** [comment]
i too have this issue, phpBB 3.3  , many thanks
